version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - nginx
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/app/src
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    tty: true
    depends_on:
      - node-1
      - node-2
      - node-3
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - app-network

  node-1:
    container_name: node-1
    build:
      context: ./node
      dockerfile: Dockerfile
    depends_on:
      - db-node-1
    ports:
      - 8000:8000
    environment:
      - PORT=:8000
      - GRPC_PORT=:8001
      - DB_DSN=db-node-1:6379
      - NODES=node-2:8011,node-3:8021
    networks:
      - app-network

  db-node-1:
    container_name: db-node-1
    image: redis:7-alpine
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - 8002:6379
    volumes:
      - node-1:/data
    networks:
      - app-network

  node-2:
    container_name: node-2
    build:
      context: ./node
      dockerfile: Dockerfile
    depends_on:
      - db-node-2
    ports:
      - 8010:8010
    environment:
      - PORT=:8010
      - GRPC_PORT=:8011
      - DB_DSN=db-node-2:6379
      - NODES=node-1:8001,node-3:8021
    networks:
      - app-network

  db-node-2:
    container_name: db-node-2
    image: redis:7-alpine
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - 8012:6379
    volumes:
      - node-2:/data
    networks:
      - app-network

  node-3:
    container_name: node-3
    build:
      context: ./node
      dockerfile: Dockerfile
    depends_on:
      - db-node-3
    ports:
      - 8020:8020
    environment:
      - PORT=:8020
      - GRPC_PORT=:8021
      - DB_DSN=db-node-3:6379
      - NODES=node-1:8001,node-2:8011
    networks:
      - app-network

  db-node-3:
    container_name: db-node-3
    image: redis:7-alpine
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - 8022:6379
    volumes:
      - node-3:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node-1:
    driver: local
  node-2:
    driver: local
  node-3:
    driver: local
